Versión mejorada con ayuda de https://www.kaggle.com/code/wissams/titanic-competition-step-by-step-using-xgboost/notebook.

In this competition, you’ll gain access to two similar datasets that include passenger information like name, age, gender, socio-economic class, etc. One dataset is titled "train.csv" and the other is titled "test.csv".

"train.csv" will contain the details of a subset of the passengers on board (891 to be exact) and importantly, will reveal whether they survived or not, also known as the “ground truth”.

The "test.csv" dataset contains similar information but does not disclose the “ground truth” for each passenger. It’s your job to predict these outcomes.

Using the patterns you find in the "train.csv" data, predict whether the other 418 passengers on board (found in test.csv) survived.

In [427]:
import pandas as pd
import numpy as np

# dataset with the ground truth
data_train = pd.read_csv("C:\\Users\\alvar\\OneDrive\\Escritorio\\PROYECTOS\\Python\\MLJupyter\\train_titanic.csv")

# dataset for which we need to predict the survival
data_test = pd.read_csv("C:\\Users\\alvar\\OneDrive\\Escritorio\\PROYECTOS\\Python\\MLJupyter\\test_titanic.csv")

El objetivo es determinar "Survived" para cada "PassengerId" del fichero "train.csv".

## Gestión inicial de los datos

In [428]:
data_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [429]:
data_test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [430]:
data_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [431]:
data_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Definición de variables:
- passengerid
- survival: 0 = No, 1 = Yes
- pclass (Ticket class): 1 = 1st, 2 = 2nd, 3 = 3rd
- name
- sex
- age: in years
- sibsp: # of siblings / spouses aboard the Titanic
- parch: # of parents / children aboard the Titanic
- ticket: ticket number
- fare
- cabin: cabin number
- embarked (port of embarkation): C = Cherbourg, Q = Queenstown, S = Southampton

## Tratamiento de los datos

Ahora quiero ver qué columnas tienen huecos vacíos para poder quitarlas o imputarlas.

In [432]:
# Shape of training data (num_rows, num_columns)
print(data_train.shape)

# Number of missing values in each column of training data
missing_val_count_by_column_train = (data_train.isnull().sum())
print(missing_val_count_by_column_train[missing_val_count_by_column_train > 0])

(891, 12)
Age         177
Cabin       687
Embarked      2
dtype: int64

In [433]:
# Shape of test data (num_rows, num_columns)
print(data_test.shape)

# Number of missing values in each column of test data
missing_val_count_by_column_test = (data_test.isnull().sum())
print(missing_val_count_by_column_test[missing_val_count_by_column_test > 0])

(418, 11)
Age       86
Fare       1
Cabin    327
dtype: int64

Vemos que la columna de cabina está practicamente vacía, pero seguramente sea porque los que no estaban en primera clase no tenían cabina asignada.

La de embarked está practicamente llena, pero son strings, así que quiero transformarla a los valores 0,1,2, e imputar los dos huecos vacíos con el puerto más frecuente.

Quito también las columnas de Ticket y Name ya que creo que no tienen tanta importancia (Ticket está relacionado con Fare).

La de edad la podemos imputar por clase y sexo.

In [434]:
# Drop ticket and name columns
reduced_data_train = data_train.drop(['Ticket'], axis=1) # 'Name'
reduced_data_test = data_test.drop(['Ticket'],axis=1)

Imputación del único valor de "Fare" que está libre. Imputo en función de 'Class' del hueco.

In [435]:
median_fare_per_class = reduced_data_test.groupby("Pclass")["Fare"].median()

def fill_fare_test(row):
    if pd.isnull(row["Fare"]):  # si la edad está vacía
        return median_fare_per_class.loc[row["Pclass"]]
    else:
        return row["Fare"]
    
# imputo el hueco de Fare del dataset test
reduced_data_test["Fare"] = reduced_data_test.apply(fill_fare_test, axis=1)

Imputacion de las edades por sexo y clase.

In [436]:
# edades medias agrupadas por clase y sexo
median_ages_train = reduced_data_train.groupby(["Pclass", "Sex"])["Age"].median()
median_ages_test = reduced_data_test.groupby(["Pclass", "Sex"])["Age"].median()

# funcion que sirve para imputar los huecos vacíos con las edades agrupadas por clase y sexo
def fill_age_train(row):
    if pd.isnull(row["Age"]):  # si la edad está vacía
        return median_ages_train.loc[row["Pclass"], row["Sex"]]
    else:
        return row["Age"]
    
def fill_age_test(row):
    if pd.isnull(row["Age"]):  # si la edad está vacía
        return median_ages_test.loc[row["Pclass"], row["Sex"]]
    else:
        return row["Age"]
    
# imputo los huecos
reduced_data_train["Age"] = reduced_data_train.apply(fill_age_train, axis=1)
reduced_data_test["Age"] = reduced_data_test.apply(fill_age_test, axis=1)

Ahora quiero hacer ordinal encoding tranformando Female = 0 y Male = 1.

In [437]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
reduced_data_train["Sex"] = encoder.fit_transform(reduced_data_train["Sex"])
reduced_data_test["Sex"] = encoder.fit_transform(reduced_data_test["Sex"])

Ahora voy a obtener la primera letra del "Cabin".

In [438]:
# obtengo la primera letra de Cabin y luego sustituyo la columna Cabin por Cabin_Letter
reduced_data_train['Cabin_Letter'] = reduced_data_train['Cabin'].str[:1]
reduced_data_train.Cabin_Letter.fillna('Unknown', inplace=True)
reduced_data_train= reduced_data_train.drop(columns=['Cabin'])

reduced_data_train.Cabin_Letter.value_counts()

C:\Users\alvar\AppData\Local\Temp\ipykernel_3652\1649161886.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reduced_data_train.Cabin_Letter.fillna('Unknown', inplace=True)

Cabin_Letter
Unknown    687
C           59
B           47
D           33
E           32
A           15
F           13
G            4
T            1
Name: count, dtype: int64

In [439]:
# Obtengo la primera letra de Cabin y luego sustituyo la columna Cabin por Cabin_Letter

reduced_data_test['Cabin_Letter'] = reduced_data_test['Cabin'].str[:1]
reduced_data_test.Cabin_Letter.fillna('Unknown', inplace=True)
reduced_data_test= reduced_data_test.drop(columns=['Cabin'])

reduced_data_test.Cabin_Letter.value_counts()

C:\Users\alvar\AppData\Local\Temp\ipykernel_3652\2062025157.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reduced_data_test.Cabin_Letter.fillna('Unknown', inplace=True)

Cabin_Letter
Unknown    327
C           35
B           18
D           13
E            9
F            8
A            7
G            1
Name: count, dtype: int64

Voy a leer los títulos de los nombres y a agrupar algunos y luego les hago ordinal encoding.

In [440]:
reduced_data_train['Title'] = reduced_data_train['Name'].str.split(', ').str[1].str.split('.').str[0]
reduced_data_test['Title'] = reduced_data_test['Name'].str.split(', ').str[1].str.split('.').str[0]

reduced_data_train['Title'].unique() # Muestro los títulos del set de train

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'the Countess',
       'Jonkheer'], dtype=object)

In [441]:
# Agrupacion de algunos titulos minoritarios

title_mapping= {'Mr':'Mr', 'Mrs':'Mrs', 'Miss':'Miss','Master':'Master', 'Don':'Rare', 'Rev':'Rare', 'Dr':'Rare', 'Mme':'Mrs', 'Ms':'Miss',
       'Major':'Rare', 'Lady':'Rare' , 'Sir':'Rare', 'Mlle':'Miss', 'Col':'Rare', 'Capt':'Rare', 'the Countess':'Rare',
       'Jonkheer':'Rare', 'Dona':'Rare'}

reduced_data_train['Title']= reduced_data_train['Title'].map(title_mapping)
reduced_data_test['Title']= reduced_data_test['Title'].map(title_mapping)

In [442]:
reduced_data_train['Title'].value_counts()

Title
Mr        517
Miss      185
Mrs       126
Master     40
Rare       23
Name: count, dtype: int64

In [443]:
reduced_data_test['Title'].value_counts()

Title
Mr        240
Miss       79
Mrs        72
Master     21
Rare        6
Name: count, dtype: int64

Ahora hago ordinal encoding de estos titulos:

Por último, lo que voy a hacer es juntar las columnas SibSp y Parch para crear la columna 'FamilySize' para generalizar más.

In [444]:
# +1 incluyendo al propio pasajero
reduced_data_train["FamilySize"] = reduced_data_train["Parch"] + reduced_data_train["SibSp"] + 1
reduced_data_test["FamilySize"] = reduced_data_test["Parch"] + reduced_data_test["SibSp"] + 1

Vamos a hacer One Hot Encoding a las columnas categóricas 'Cabin_Letter' y 'Title' para ver si mejora así la solución. Es importante hacer OHE ya que si se hace solo Ordinal Encoding, el modelo de ML puede crear relaciones falsas al haber un orden de números fictíceo.

In [445]:
from sklearn.preprocessing import OneHotEncoder

# Crear el encoder
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Fit y transform al train
OH_reduced_train = pd.DataFrame(
    OH_encoder.fit_transform(reduced_data_train[['Cabin_Letter','Title','Embarked']]),
    index=reduced_data_train.index,
    columns=OH_encoder.get_feature_names_out(['Cabin_Letter','Title','Embarked'])
)

# Transform al test (con los mismos nombres de columnas)
OH_reduced_test = pd.DataFrame(
    OH_encoder.transform(reduced_data_test[['Cabin_Letter','Title','Embarked']]),
    index=reduced_data_test.index,
    columns=OH_encoder.get_feature_names_out(['Cabin_Letter','Title','Embarked']))

# Eliminar columnas originales categóricas
reduced_data_train = reduced_data_train.drop(['Cabin_Letter','Title','Embarked'], axis=1)
reduced_data_test = reduced_data_test.drop(['Cabin_Letter','Title','Embarked'], axis=1)

# Concatenar de nuevo las columnas OHE
reduced_data_train = pd.concat([reduced_data_train, OH_reduced_train], axis=1)
reduced_data_test = pd.concat([reduced_data_test, OH_reduced_test], axis=1)

Ahora quiero normalizar los valores de 'Fare', 'Age' y 'FamilySize' para que tomen valores entre 0 y 1.

In [446]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

reduced_data_train['scaledFare'] = scaler.fit_transform(reduced_data_train[['Fare']])
reduced_data_test['scaledFare'] = scaler.fit_transform(reduced_data_test[['Fare']])

reduced_data_train['scaledAge'] = scaler.fit_transform(reduced_data_train[['Age']])
reduced_data_test['scaledAge'] = scaler.fit_transform(reduced_data_test[['Age']])

reduced_data_train['scaledFamily'] = scaler.fit_transform(reduced_data_train[['FamilySize']])
reduced_data_test['scaledFamily'] = scaler.fit_transform(reduced_data_test[['FamilySize']])

In [447]:
reduced_data_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,FamilySize,...,Title_Mr,Title_Mrs,Title_Rare,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan,scaledFare,scaledAge,scaledFamily
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,7.2500,2,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.014151,0.271174,0.1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,71.2833,2,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.139136,0.472229,0.1
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,7.9250,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.015469,0.321438,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,53.1000,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.103644,0.434531,0.1
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,8.0500,1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.015713,0.434531,0.0

In [448]:
reduced_data_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Fare,FamilySize,Cabin_Letter_A,...,Title_Mr,Title_Mrs,Title_Rare,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan,scaledFare,scaledAge,scaledFamily
0,892,3,"Kelly, Mr. James",1,34.5,0,0,7.8292,1,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.015282,0.452723,0.0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,7.0000,2,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.013663,0.617566,0.1
2,894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,9.6875,1,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.018909,0.815377,0.0
3,895,3,"Wirz, Mr. Albert",1,27.0,0,0,8.6625,1,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.016908,0.353818,0.0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,12.2875,3,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.023984,0.287881,0.2

In [449]:
# Number of missing values in each column of training data
missing_val_count_by_column_train = (reduced_data_train.isnull().sum())
print(missing_val_count_by_column_train[missing_val_count_by_column_train > 0])

Series([], dtype: int64)

In [450]:
# Number of missing values in each column of test data
missing_val_count_by_column_test = (reduced_data_test.isnull().sum())
print(missing_val_count_by_column_test[missing_val_count_by_column_test > 0])

Series([], dtype: int64)

Quiero ver el nombre de las columnas para luego saber cuáles usar para el RF y el XGB.

In [451]:
reduced_data_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Fare', 'FamilySize', 'Cabin_Letter_A', 'Cabin_Letter_B',
       'Cabin_Letter_C', 'Cabin_Letter_D', 'Cabin_Letter_E', 'Cabin_Letter_F',
       'Cabin_Letter_G', 'Cabin_Letter_T', 'Cabin_Letter_Unknown',
       'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Rare',
       'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Embarked_nan', 'scaledFare',
       'scaledAge', 'scaledFamily'],
      dtype='object')

In [452]:
reduced_data_test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'FamilySize', 'Cabin_Letter_A', 'Cabin_Letter_B', 'Cabin_Letter_C',
       'Cabin_Letter_D', 'Cabin_Letter_E', 'Cabin_Letter_F', 'Cabin_Letter_G',
       'Cabin_Letter_T', 'Cabin_Letter_Unknown', 'Title_Master', 'Title_Miss',
       'Title_Mr', 'Title_Mrs', 'Title_Rare', 'Embarked_C', 'Embarked_Q',
       'Embarked_S', 'Embarked_nan', 'scaledFare', 'scaledAge',
       'scaledFamily'],
      dtype='object')

## Random Forests

In [453]:
from sklearn.tree import DecisionTreeClassifier # Classifier para discreto, Regressor para continuo

# Guardamos el predicition target 
y_train = reduced_data_train.Survived 
X_train = reduced_data_train[['Sex','scaledAge','scaledFare','Pclass','scaledFamily','Cabin_Letter_A','Cabin_Letter_B',
                              'Cabin_Letter_C','Cabin_Letter_D','Cabin_Letter_E','Cabin_Letter_F','Cabin_Letter_G',
                              'Cabin_Letter_T','Cabin_Letter_Unknown','Title_Master','Title_Miss','Title_Mr','Title_Mrs',
                              'Title_Rare','Embarked_C','Embarked_Q','Embarked_S','Embarked_nan']]

X_test = reduced_data_test[['Sex','scaledAge','scaledFare','Pclass','scaledFamily','Cabin_Letter_A','Cabin_Letter_B',
                              'Cabin_Letter_C','Cabin_Letter_D','Cabin_Letter_E','Cabin_Letter_F','Cabin_Letter_G',
                              'Cabin_Letter_T','Cabin_Letter_Unknown','Title_Master','Title_Miss','Title_Mr','Title_Mrs',
                              'Title_Rare','Embarked_C','Embarked_Q','Embarked_S','Embarked_nan']] 

# Define model. Specify a number for random_state to ensure same results each run
titanic_model = DecisionTreeClassifier(max_leaf_nodes=100,random_state=1,criterion='gini',max_depth=7,min_samples_split=3)

# Fit model
titanic_model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=7, max_leaf_nodes=100, min_samples_split=3,
                       random_state=1)

In [454]:
predictions = titanic_model.predict(X_test)

## Saving the solutions for Random Forest

In [455]:
solution = pd.DataFrame({'PassengerId': reduced_data_test.PassengerId, 'Survived': predictions})
solution.to_csv('submission.csv', index=False)

colsurv_rf = solution['Survived']

## XGBoost

Necesitamos primero definir X_train y y_train y luego dividirlo con split para poder hacer la validación con XGBoost.

In [456]:
from sklearn.model_selection import train_test_split

# Dividimos el train original en train + valid
X_train_new, X_valid, y_train_new, y_valid = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
#test_size = 0.2 implica que el 20% de X_train va para X_valid (test)

Tuneamos y generamos el modelo de XGBoost:

In [457]:
#from sklearn.model_selection import RandomizedSearchCV

#params = {
#    "max_depth": [3,4,5,6],
#    "min_child_weight": [3,5,6],
#    "subsample": [0.6,0.75,0.9],
#    "colsample_bytree": [0.6,0.75,0.8,0.9],
#    "gamma": [0, 0.1, 0.2, 0.4],
#    "reg_alpha": [0, 0.01, 0.05, 0.1],
#    "learning_rate": [0.01,0.05,0.1]
#}
 

#search = RandomizedSearchCV(
#    XGBClassifier(n_estimators=1000, eval_metric="logloss", random_state=42),
#    param_distributions=params, n_iter=40, cv=5, scoring="roc_auc", n_jobs=-1, verbose=1
#)
#search.fit(X_train_new, y_train_new)
#best = search.best_estimator_

In [458]:
#print(best)

In [477]:
from xgboost import XGBClassifier

titanic_xgmodel = XGBClassifier(
    n_estimators=1000,        # número de árboles
    learning_rate=0.001,      # tamaño de los pasos de boosting
    max_depth=5,             # profundidad máxima de cada árbol
    subsample=0.8,           # fracción de datos por árbol
    colsample_bytree=0.6,    # fracción de features por árbol
    use_label_encoder=False,
    eval_metric="logloss",
    early_stopping_rounds=50, 
    verbose=False,
    objective="binary:logistic",
    min_child_weight= 5,
    gamma = 0.1)

titanic_xgmodel.fit(X_train_new, y_train_new, eval_set=[(X_valid, y_valid)])

[0]	validation_0-logloss:0.68051
[1]	validation_0-logloss:0.68008
[2]	validation_0-logloss:0.67964
[3]	validation_0-logloss:0.67921
[4]	validation_0-logloss:0.67876
[5]	validation_0-logloss:0.67833
[6]	validation_0-logloss:0.67790
[7]	validation_0-logloss:0.67743
[8]	validation_0-logloss:0.67701
[9]	validation_0-logloss:0.67661
[10]	validation_0-logloss:0.67625
[11]	validation_0-logloss:0.67583
[12]	validation_0-logloss:0.67547
[13]	validation_0-logloss:0.67511
[14]	validation_0-logloss:0.67467
[15]	validation_0-logloss:0.67439
[16]	validation_0-logloss:0.67396
[17]	validation_0-logloss:0.67352
[18]	validation_0-logloss:0.67316
[19]	validation_0-logloss:0.67279
[20]	validation_0-logloss:0.67237
[21]	validation_0-logloss:0.67200
[22]	validation_0-logloss:0.67165
[23]	validation_0-logloss:0.67130
[24]	validation_0-logloss:0.67088
[25]	validation_0-logloss:0.67047
[26]	validation_0-logloss:0.67016
[27]	validation_0-logloss:0.66982
[28]	validation_0-logloss:0.66944
[29]	validation_0-logloss:0.66905
[30]	validation_0-logloss:0.66861
[31]	validation_0-logloss:0.66826
[32]	validation_0-logloss:0.66784
[33]	validation_0-logloss:0.66766
[34]	validation_0-logloss:0.66732
[35]	validation_0-logloss:0.66689
[36]	validation_0-logloss:0.66651
[37]	validation_0-logloss:0.66631
[38]	validation_0-logloss:0.66591
[39]	validation_0-logloss:0.66568
[40]	validation_0-logloss:0.66531
[41]	validation_0-logloss:0.66492
[42]	validation_0-logloss:0.66450
[43]	validation_0-logloss:0.66411
[44]	validation_0-logloss:0.66378
[45]	validation_0-logloss:0.66335
[46]	validation_0-logloss:0.66296
[47]	validation_0-logloss:0.66276
[48]	validation_0-logloss:0.66233
[49]	validation_0-logloss:0.66194
[50]	validation_0-logloss:0.66159
[51]	validation_0-logloss:0.66126
[52]	validation_0-logloss:0.66104
[53]	validation_0-logloss:0.66063
[54]	validation_0-logloss:0.66028
[55]	validation_0-logloss:0.65998
[56]	validation_0-logloss:0.65960
[57]	validation_0-logloss:0.65919
[58]	validation_0-logloss:0.65879
[59]	validation_0-logloss:0.65840
[60]	validation_0-logloss:0.65808

c:\Users\alvar\anaconda3\Lib\site-packages\xgboost\callback.py:386: UserWarning: [21:56:40] WARNING: C:\b\abs_d97hy_84m6\croot\xgboost-split_1749630932152\work\src\learner.cc:738:
Parameters: { "use_label_encoder", "verbose" } are not used.

  self.starting_round = model.num_boosted_rounds()

[61]	validation_0-logloss:0.65774
[62]	validation_0-logloss:0.65737
[63]	validation_0-logloss:0.65711
[64]	validation_0-logloss:0.65669
[65]	validation_0-logloss:0.65630
[66]	validation_0-logloss:0.65592
[67]	validation_0-logloss:0.65557
[68]	validation_0-logloss:0.65519
[69]	validation_0-logloss:0.65478
[70]	validation_0-logloss:0.65437
[71]	validation_0-logloss:0.65399
[72]	validation_0-logloss:0.65357
[73]	validation_0-logloss:0.65322
[74]	validation_0-logloss:0.65285
[75]	validation_0-logloss:0.65244
[76]	validation_0-logloss:0.65224
[77]	validation_0-logloss:0.65183
[78]	validation_0-logloss:0.65149
[79]	validation_0-logloss:0.65110
[80]	validation_0-logloss:0.65071
[81]	validation_0-logloss:0.65034
[82]	validation_0-logloss:0.64996
[83]	validation_0-logloss:0.64961
[84]	validation_0-logloss:0.64929
[85]	validation_0-logloss:0.64892
[86]	validation_0-logloss:0.64853
[87]	validation_0-logloss:0.64817
[88]	validation_0-logloss:0.64779
[89]	validation_0-logloss:0.64750
[90]	validation_0-logloss:0.64718
[91]	validation_0-logloss:0.64678
[92]	validation_0-logloss:0.64649
[93]	validation_0-logloss:0.64614
[94]	validation_0-logloss:0.64578
[95]	validation_0-logloss:0.64548
[96]	validation_0-logloss:0.64514
[97]	validation_0-logloss:0.64479
[98]	validation_0-logloss:0.64460
[99]	validation_0-logloss:0.64426
[100]	validation_0-logloss:0.64390
[101]	validation_0-logloss:0.64357
[102]	validation_0-logloss:0.64322
[103]	validation_0-logloss:0.64284
[104]	validation_0-logloss:0.64250
[105]	validation_0-logloss:0.64213
[106]	validation_0-logloss:0.64184
[107]	validation_0-logloss:0.64149
[108]	validation_0-logloss:0.64126
[109]	validation_0-logloss:0.64093
[110]	validation_0-logloss:0.64064
[111]	validation_0-logloss:0.64030
[112]	validation_0-logloss:0.63995
[113]	validation_0-logloss:0.63963
[114]	validation_0-logloss:0.63928
[115]	validation_0-logloss:0.63895
[116]	validation_0-logloss:0.63863
[117]	validation_0-logloss:0.63837
[118]	validation_0-logloss:0.63802
[119]	validation_0-logloss:0.63787
[120]	validation_0-logloss:0.63761
[121]	validation_0-logloss:0.63726
[122]	validation_0-logloss:0.63702
[123]	validation_0-logloss:0.63671
[124]	validation_0-logloss:0.63653
[125]	validation_0-logloss:0.63617
[126]	validation_0-logloss:0.63583
[127]	validation_0-logloss:0.63550
[128]	validation_0-logloss:0.63516
[129]	validation_0-logloss:0.63482
[130]	validation_0-logloss:0.63458
[131]	validation_0-logloss:0.63422
[132]	validation_0-logloss:0.63392
[133]	validation_0-logloss:0.63358
[134]	validation_0-logloss:0.63320
[135]	validation_0-logloss:0.63293
[136]	validation_0-logloss:0.63279
[137]	validation_0-logloss:0.63250
[138]	validation_0-logloss:0.63217
[139]	validation_0-logloss:0.63180
[140]	validation_0-logloss:0.63147
[141]	validation_0-logloss:0.63112
[142]	validation_0-logloss:0.63079
[143]	validation_0-logloss:0.63052
[144]	validation_0-logloss:0.63022
[145]	validation_0-logloss:0.62989
[146]	validation_0-logloss:0.62952
[147]	validation_0-logloss:0.62924
[148]	validation_0-logloss:0.62893
[149]	validation_0-logloss:0.62858
[150]	validation_0-logloss:0.62827
[151]	validation_0-logloss:0.62795
[152]	validation_0-logloss:0.62771
[153]	validation_0-logloss:0.62736
[154]	validation_0-logloss:0.62712
[155]	validation_0-logloss:0.62680
[156]	validation_0-logloss:0.62644
[157]	validation_0-logloss:0.62618
[158]	validation_0-logloss:0.62588
[159]	validation_0-logloss:0.62568
[160]	validation_0-logloss:0.62551
[161]	validation_0-logloss:0.62518
[162]	validation_0-logloss:0.62484
[163]	validation_0-logloss:0.62456
[164]	validation_0-logloss:0.62426
[165]	validation_0-logloss:0.62393
[166]	validation_0-logloss:0.62360
[167]	validation_0-logloss:0.62345
[168]	validation_0-logloss:0.62325
[169]	validation_0-logloss:0.62299
[170]	validation_0-logloss:0.62275
[171]	validation_0-logloss:0.62248
[172]	validation_0-logloss:0.62222
[173]	validation_0-logloss:0.62190
[174]	validation_0-logloss:0.62157
[175]	validation_0-logloss:0.62121
[176]	validation_0-logloss:0.62103
[177]	validation_0-logloss:0.62069
[178]	validation_0-logloss:0.62042
[179]	validation_0-logloss:0.62011
[180]	validation_0-logloss:0.61983
[181]	validation_0-logloss:0.61969
[182]	validation_0-logloss:0.61943
[183]	validation_0-logloss:0.61910
[184]	validation_0-logloss:0.61887
[185]	validation_0-logloss:0.61853
[186]	validation_0-logloss:0.61821
[187]	validation_0-logloss:0.61790
[188]	validation_0-logloss:0.61762
[189]	validation_0-logloss:0.61733
[190]	validation_0-logloss:0.61705
[191]	validation_0-logloss:0.61675
[192]	validation_0-logloss:0.61658
[193]	validation_0-logloss:0.61626
[194]	validation_0-logloss:0.61594
[195]	validation_0-logloss:0.61561
[196]	validation_0-logloss:0.61531
[197]	validation_0-logloss:0.61499
[198]	validation_0-logloss:0.61469
[199]	validation_0-logloss:0.61436
[200]	validation_0-logloss:0.61409
[201]	validation_0-logloss:0.61382
[202]	validation_0-logloss:0.61353
[203]	validation_0-logloss:0.61331
[204]	validation_0-logloss:0.61298
[205]	validation_0-logloss:0.61273
[206]	validation_0-logloss:0.61244
[207]	validation_0-logloss:0.61217
[208]	validation_0-logloss:0.61189
[209]	validation_0-logloss:0.61162
[210]	validation_0-logloss:0.61131
[211]	validation_0-logloss:0.61099
[212]	validation_0-logloss:0.61072
[213]	validation_0-logloss:0.61040
[214]	validation_0-logloss:0.61010
[215]	validation_0-logloss:0.60979
[216]	validation_0-logloss:0.60951
[217]	validation_0-logloss:0.60922
[218]	validation_0-logloss:0.60890
[219]	validation_0-logloss:0.60858
[220]	validation_0-logloss:0.60831
[221]	validation_0-logloss:0.60801
[222]	validation_0-logloss:0.60772
[223]	validation_0-logloss:0.60742
[224]	validation_0-logloss:0.60710
[225]	validation_0-logloss:0.60681
[226]	validation_0-logloss:0.60652
[227]	validation_0-logloss:0.60621
[228]	validation_0-logloss:0.60596
[229]	validation_0-logloss:0.60566
[230]	validation_0-logloss:0.60541
[231]	validation_0-logloss:0.60512
[232]	validation_0-logloss:0.60484
[233]	validation_0-logloss:0.60472
[234]	validation_0-logloss:0.60441
[235]	validation_0-logloss:0.60411
[236]	validation_0-logloss:0.60380
[237]	validation_0-logloss:0.60353
[238]	validation_0-logloss:0.60323
[239]	validation_0-logloss:0.60295
[240]	validation_0-logloss:0.60272
[241]	validation_0-logloss:0.60243
[242]	validation_0-logloss:0.60216
[243]	validation_0-logloss:0.60189
[244]	validation_0-logloss:0.60162
[245]	validation_0-logloss:0.60132
[246]	validation_0-logloss:0.60105
[247]	validation_0-logloss:0.60078
[248]	validation_0-logloss:0.60052
[249]	validation_0-logloss:0.60028
[250]	validation_0-logloss:0.59999
[251]	validation_0-logloss:0.59971
[252]	validation_0-logloss:0.59953
[253]	validation_0-logloss:0.59923
[254]	validation_0-logloss:0.59893
[255]	validation_0-logloss:0.59864
[256]	validation_0-logloss:0.59838
[257]	validation_0-logloss:0.59818
[258]	validation_0-logloss:0.59792
[259]	validation_0-logloss:0.59765
[260]	validation_0-logloss:0.59736
[261]	validation_0-logloss:0.59709
[262]	validation_0-logloss:0.59682
[263]	validation_0-logloss:0.59668
[264]	validation_0-logloss:0.59651
[265]	validation_0-logloss:0.59631
[266]	validation_0-logloss:0.59603
[267]	validation_0-logloss:0.59575
[268]	validation_0-logloss:0.59553
[269]	validation_0-logloss:0.59525
[270]	validation_0-logloss:0.59499
[271]	validation_0-logloss:0.59478
[272]	validation_0-logloss:0.59452
[273]	validation_0-logloss:0.59424
[274]	validation_0-logloss:0.59400
[275]	validation_0-logloss:0.59374
[276]	validation_0-logloss:0.59344
[277]	validation_0-logloss:0.59327
[278]	validation_0-logloss:0.59301
[279]	validation_0-logloss:0.59273
[280]	validation_0-logloss:0.59248
[281]	validation_0-logloss:0.59221
[282]	validation_0-logloss:0.59200
[283]	validation_0-logloss:0.59173
[284]	validation_0-logloss:0.59155
[285]	validation_0-logloss:0.59128
[286]	validation_0-logloss:0.59105
[287]	validation_0-logloss:0.59079
[288]	validation_0-logloss:0.59052
[289]	validation_0-logloss:0.59027
[290]	validation_0-logloss:0.59001
[291]	validation_0-logloss:0.58980
[292]	validation_0-logloss:0.58953
[293]	validation_0-logloss:0.58931
[294]	validation_0-logloss:0.58903
[295]	validation_0-logloss:0.58873
[296]	validation_0-logloss:0.58853
[297]	validation_0-logloss:0.58842
[298]	validation_0-logloss:0.58818
[299]	validation_0-logloss:0.58789
[300]	validation_0-logloss:0.58761
[301]	validation_0-logloss:0.58747
[302]	validation_0-logloss:0.58723
[303]	validation_0-logloss:0.58694
[304]	validation_0-logloss:0.58668
[305]	validation_0-logloss:0.58638
[306]	validation_0-logloss:0.58617
[307]	validation_0-logloss:0.58590
[308]	validation_0-logloss:0.58568
[309]	validation_0-logloss:0.58546
[310]	validation_0-logloss:0.58519
[311]	validation_0-logloss:0.58491
[312]	validation_0-logloss:0.58465
[313]	validation_0-logloss:0.58438
[314]	validation_0-logloss:0.58414
[315]	validation_0-logloss:0.58394
[316]	validation_0-logloss:0.58368
[317]	validation_0-logloss:0.58344
[318]	validation_0-logloss:0.58325
[319]	validation_0-logloss:0.58297
[320]	validation_0-logloss:0.58271
[321]	validation_0-logloss:0.58247
[322]	validation_0-logloss:0.58234
[323]	validation_0-logloss:0.58212
[324]	validation_0-logloss:0.58191
[325]	validation_0-logloss:0.58171
[326]	validation_0-logloss:0.58145
[327]	validation_0-logloss:0.58125
[328]	validation_0-logloss:0.58104
[329]	validation_0-logloss:0.58080
[330]	validation_0-logloss:0.58055
[331]	validation_0-logloss:0.58033
[332]	validation_0-logloss:0.58008
[333]	validation_0-logloss:0.57988
[334]	validation_0-logloss:0.57963
[335]	validation_0-logloss:0.57936
[336]	validation_0-logloss:0.57924
[337]	validation_0-logloss:0.57898
[338]	validation_0-logloss:0.57875
[339]	validation_0-logloss:0.57852
[340]	validation_0-logloss:0.57829
[341]	validation_0-logloss:0.57809
[342]	validation_0-logloss:0.57793
[343]	validation_0-logloss:0.57771
[344]	validation_0-logloss:0.57748
[345]	validation_0-logloss:0.57726
[346]	validation_0-logloss:0.57701
[347]	validation_0-logloss:0.57677
[348]	validation_0-logloss:0.57662
[349]	validation_0-logloss:0.57638
[350]	validation_0-logloss:0.57616
[351]	validation_0-logloss:0.57592
[352]	validation_0-logloss:0.57566
[353]	validation_0-logloss:0.57544
[354]	validation_0-logloss:0.57522
[355]	validation_0-logloss:0.57497
[356]	validation_0-logloss:0.57478
[357]	validation_0-logloss:0.57456
[358]	validation_0-logloss:0.57432
[359]	validation_0-logloss:0.57410
[360]	validation_0-logloss:0.57385
[361]	validation_0-logloss:0.57361
[362]	validation_0-logloss:0.57337
[363]	validation_0-logloss:0.57319
[364]	validation_0-logloss:0.57294
[365]	validation_0-logloss:0.57270
[366]	validation_0-logloss:0.57245
[367]	validation_0-logloss:0.57220
[368]	validation_0-logloss:0.57196
[369]	validation_0-logloss:0.57178
[370]	validation_0-logloss:0.57154
[371]	validation_0-logloss:0.57132
[372]	validation_0-logloss:0.57108
[373]	validation_0-logloss:0.57091
[374]	validation_0-logloss:0.57071
[375]	validation_0-logloss:0.57053
[376]	validation_0-logloss:0.57028
[377]	validation_0-logloss:0.57005
[378]	validation_0-logloss:0.56993
[379]	validation_0-logloss:0.56968
[380]	validation_0-logloss:0.56951
[381]	validation_0-logloss:0.56934
[382]	validation_0-logloss:0.56914
[383]	validation_0-logloss:0.56895
[384]	validation_0-logloss:0.56875
[385]	validation_0-logloss:0.56852
[386]	validation_0-logloss:0.56829
[387]	validation_0-logloss:0.56804
[388]	validation_0-logloss:0.56781
[389]	validation_0-logloss:0.56758
[390]	validation_0-logloss:0.56738
[391]	validation_0-logloss:0.56719
[392]	validation_0-logloss:0.56694
[393]	validation_0-logloss:0.56676
[394]	validation_0-logloss:0.56661
[395]	validation_0-logloss:0.56635
[396]	validation_0-logloss:0.56614
[397]	validation_0-logloss:0.56591
[398]	validation_0-logloss:0.56580
[399]	validation_0-logloss:0.56564
[400]	validation_0-logloss:0.56546
[401]	validation_0-logloss:0.56524
[402]	validation_0-logloss:0.56503
[403]	validation_0-logloss:0.56481
[404]	validation_0-logloss:0.56468
[405]	validation_0-logloss:0.56449
[406]	validation_0-logloss:0.56436
[407]	validation_0-logloss:0.56414
[408]	validation_0-logloss:0.56390
[409]	validation_0-logloss:0.56379
[410]	validation_0-logloss:0.56360
[411]	validation_0-logloss:0.56339
[412]	validation_0-logloss:0.56317
[413]	validation_0-logloss:0.56299
[414]	validation_0-logloss:0.56283
[415]	validation_0-logloss:0.56261
[416]	validation_0-logloss:0.56237
[417]	validation_0-logloss:0.56221
[418]	validation_0-logloss:0.56198
[419]	validation_0-logloss:0.56176
[420]	validation_0-logloss:0.56155
[421]	validation_0-logloss:0.56136
[422]	validation_0-logloss:0.56121
[423]	validation_0-logloss:0.56102
[424]	validation_0-logloss:0.56081
[425]	validation_0-logloss:0.56062
[426]	validation_0-logloss:0.56044
[427]	validation_0-logloss:0.56019
[428]	validation_0-logloss:0.56002
[429]	validation_0-logloss:0.55982
[430]	validation_0-logloss:0.55972
[431]	validation_0-logloss:0.55956
[432]	validation_0-logloss:0.55945
[433]	validation_0-logloss:0.55922
[434]	validation_0-logloss:0.55901
[435]	validation_0-logloss:0.55876
[436]	validation_0-logloss:0.55853
[437]	validation_0-logloss:0.55830
[438]	validation_0-logloss:0.55816
[439]	validation_0-logloss:0.55792
[440]	validation_0-logloss:0.55773
[441]	validation_0-logloss:0.55752
[442]	validation_0-logloss:0.55729
[443]	validation_0-logloss:0.55708
[444]	validation_0-logloss:0.55684
[445]	validation_0-logloss:0.55667
[446]	validation_0-logloss:0.55646
[447]	validation_0-logloss:0.55623
[448]	validation_0-logloss:0.55601
[449]	validation_0-logloss:0.55583
[450]	validation_0-logloss:0.55570
[451]	validation_0-logloss:0.55553
[452]	validation_0-logloss:0.55535
[453]	validation_0-logloss:0.55524
[454]	validation_0-logloss:0.55503
[455]	validation_0-logloss:0.55486
[456]	validation_0-logloss:0.55466
[457]	validation_0-logloss:0.55445
[458]	validation_0-logloss:0.55424
[459]	validation_0-logloss:0.55405
[460]	validation_0-logloss:0.55381
[461]	validation_0-logloss:0.55366
[462]	validation_0-logloss:0.55343
[463]	validation_0-logloss:0.55329
[464]	validation_0-logloss:0.55313
[465]	validation_0-logloss:0.55292
[466]	validation_0-logloss:0.55271
[467]	validation_0-logloss:0.55249
[468]	validation_0-logloss:0.55227
[469]	validation_0-logloss:0.55209
[470]	validation_0-logloss:0.55187
[471]	validation_0-logloss:0.55167
[472]	validation_0-logloss:0.55146
[473]	validation_0-logloss:0.55126
[474]	validation_0-logloss:0.55111
[475]	validation_0-logloss:0.55094
[476]	validation_0-logloss:0.55077
[477]	validation_0-logloss:0.55056
[478]	validation_0-logloss:0.55035
[479]	validation_0-logloss:0.55013
[480]	validation_0-logloss:0.54994
[481]	validation_0-logloss:0.54974
[482]	validation_0-logloss:0.54957
[483]	validation_0-logloss:0.54935
[484]	validation_0-logloss:0.54918
[485]	validation_0-logloss:0.54899
[486]	validation_0-logloss:0.54879
[487]	validation_0-logloss:0.54858
[488]	validation_0-logloss:0.54843
[489]	validation_0-logloss:0.54829
[490]	validation_0-logloss:0.54808
[491]	validation_0-logloss:0.54788
[492]	validation_0-logloss:0.54769
[493]	validation_0-logloss:0.54751
[494]	validation_0-logloss:0.54736
[495]	validation_0-logloss:0.54716
[496]	validation_0-logloss:0.54696
[497]	validation_0-logloss:0.54675
[498]	validation_0-logloss:0.54653
[499]	validation_0-logloss:0.54634
[500]	validation_0-logloss:0.54612
[501]	validation_0-logloss:0.54592
[502]	validation_0-logloss:0.54575
[503]	validation_0-logloss:0.54559
[504]	validation_0-logloss:0.54539
[505]	validation_0-logloss:0.54527
[506]	validation_0-logloss:0.54509
[507]	validation_0-logloss:0.54497
[508]	validation_0-logloss:0.54478
[509]	validation_0-logloss:0.54459
[510]	validation_0-logloss:0.54440
[511]	validation_0-logloss:0.54421
[512]	validation_0-logloss:0.54406
[513]	validation_0-logloss:0.54387
[514]	validation_0-logloss:0.54365
[515]	validation_0-logloss:0.54348
[516]	validation_0-logloss:0.54334
[517]	validation_0-logloss:0.54316
[518]	validation_0-logloss:0.54300
[519]	validation_0-logloss:0.54286
[520]	validation_0-logloss:0.54276
[521]	validation_0-logloss:0.54255
[522]	validation_0-logloss:0.54238
[523]	validation_0-logloss:0.54219
[524]	validation_0-logloss:0.54199
[525]	validation_0-logloss:0.54179
[526]	validation_0-logloss:0.54164
[527]	validation_0-logloss:0.54147
[528]	validation_0-logloss:0.54128
[529]	validation_0-logloss:0.54110
[530]	validation_0-logloss:0.54089
[531]	validation_0-logloss:0.54077
[532]	validation_0-logloss:0.54061
[533]	validation_0-logloss:0.54047
[534]	validation_0-logloss:0.54028
[535]	validation_0-logloss:0.54014
[536]	validation_0-logloss:0.54001
[537]	validation_0-logloss:0.53984
[538]	validation_0-logloss:0.53965
[539]	validation_0-logloss:0.53955
[540]	validation_0-logloss:0.53939
[541]	validation_0-logloss:0.53918
[542]	validation_0-logloss:0.53898
[543]	validation_0-logloss:0.53879
[544]	validation_0-logloss:0.53862
[545]	validation_0-logloss:0.53844
[546]	validation_0-logloss:0.53825
[547]	validation_0-logloss:0.53807
[548]	validation_0-logloss:0.53793
[549]	validation_0-logloss:0.53773
[550]	validation_0-logloss:0.53756
[551]	validation_0-logloss:0.53742
[552]	validation_0-logloss:0.53726
[553]	validation_0-logloss:0.53708
[554]	validation_0-logloss:0.53691
[555]	validation_0-logloss:0.53675
[556]	validation_0-logloss:0.53660
[557]	validation_0-logloss:0.53642
[558]	validation_0-logloss:0.53623
[559]	validation_0-logloss:0.53609
[560]	validation_0-logloss:0.53596
[561]	validation_0-logloss:0.53577
[562]	validation_0-logloss:0.53559
[563]	validation_0-logloss:0.53544
[564]	validation_0-logloss:0.53526
[565]	validation_0-logloss:0.53511
[566]	validation_0-logloss:0.53494
[567]	validation_0-logloss:0.53477
[568]	validation_0-logloss:0.53464
[569]	validation_0-logloss:0.53445
[570]	validation_0-logloss:0.53435
[571]	validation_0-logloss:0.53417
[572]	validation_0-logloss:0.53398
[573]	validation_0-logloss:0.53381
[574]	validation_0-logloss:0.53361
[575]	validation_0-logloss:0.53345
[576]	validation_0-logloss:0.53326
[577]	validation_0-logloss:0.53317
[578]	validation_0-logloss:0.53299
[579]	validation_0-logloss:0.53290
[580]	validation_0-logloss:0.53275
[581]	validation_0-logloss:0.53256
[582]	validation_0-logloss:0.53239
[583]	validation_0-logloss:0.53224
[584]	validation_0-logloss:0.53205
[585]	validation_0-logloss:0.53190
[586]	validation_0-logloss:0.53174
[587]	validation_0-logloss:0.53164
[588]	validation_0-logloss:0.53152
[589]	validation_0-logloss:0.53134
[590]	validation_0-logloss:0.53124
[591]	validation_0-logloss:0.53107
[592]	validation_0-logloss:0.53090
[593]	validation_0-logloss:0.53073
[594]	validation_0-logloss:0.53060
[595]	validation_0-logloss:0.53045
[596]	validation_0-logloss:0.53028
[597]	validation_0-logloss:0.53009
[598]	validation_0-logloss:0.52996
[599]	validation_0-logloss:0.52982
[600]	validation_0-logloss:0.52973
[601]	validation_0-logloss:0.52956
[602]	validation_0-logloss:0.52937
[603]	validation_0-logloss:0.52920
[604]	validation_0-logloss:0.52903
[605]	validation_0-logloss:0.52886
[606]	validation_0-logloss:0.52869
[607]	validation_0-logloss:0.52862
[608]	validation_0-logloss:0.52849
[609]	validation_0-logloss:0.52833
[610]	validation_0-logloss:0.52820
[611]	validation_0-logloss:0.52803
[612]	validation_0-logloss:0.52785
[613]	validation_0-logloss:0.52770
[614]	validation_0-logloss:0.52758
[615]	validation_0-logloss:0.52745
[616]	validation_0-logloss:0.52731
[617]	validation_0-logloss:0.52713
[618]	validation_0-logloss:0.52700
[619]	validation_0-logloss:0.52686
[620]	validation_0-logloss:0.52675
[621]	validation_0-logloss:0.52661
[622]	validation_0-logloss:0.52644
[623]	validation_0-logloss:0.52629
[624]	validation_0-logloss:0.52611
[625]	validation_0-logloss:0.52597
[626]	validation_0-logloss:0.52581
[627]	validation_0-logloss:0.52567
[628]	validation_0-logloss:0.52551
[629]	validation_0-logloss:0.52537
[630]	validation_0-logloss:0.52520
[631]	validation_0-logloss:0.52505
[632]	validation_0-logloss:0.52487

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6, device=None, early_stopping_rounds=50,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0.1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.001, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=None,
              num_parallel_tree=None, ...)

In [478]:
predictions_xgb = titanic_xgmodel.predict(X_test)

## Saving the solutions for XGBoost

In [479]:
solution = pd.DataFrame({'PassengerId': reduced_data_test.PassengerId, 'Survived': predictions_xgb})
solution.to_csv('submission.csv', index=False)

colsurv_xgb = solution['Survived']

## AdaBoost

In [480]:
from sklearn.ensemble import AdaBoostClassifier

In [481]:
ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=5),n_estimators=500,learning_rate=0.0001,random_state=42
)

ada_clf.fit(X_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=5),
                   learning_rate=0.0001, n_estimators=500, random_state=42)

In [482]:
predictions_ada = ada_clf.predict(X_test)

## Saving solutions for AdaBoost

In [483]:
solution = pd.DataFrame({'PassengerId': reduced_data_test.PassengerId, 'Survived': predictions_ada})
solution.to_csv('submission.csv', index=False)

colsurv_ada = solution['Survived']

## Comparing Random Forest and XGBoost solutions with the exact ones

In [484]:
perfect_solution = pd.read_csv("C:\\Users\\alvar\\OneDrive\\Escritorio\\PROYECTOS\\Python\\MLJupyter\\checksubmission_titanic.csv")

colsurv_perf = perfect_solution['Survived']

In [485]:
diff_rf = colsurv_rf != colsurv_perf
diff_xgb = colsurv_xgb != colsurv_perf  # True where values differ
diff_ada = colsurv_ada != colsurv_perf

total_cells_rf = diff_rf.size              # total number of cells (418)
total_cells_xgb = diff_xgb.size   
total_cells_ada = diff_ada.size

num_differences_rf = diff_rf.sum().sum()
num_differences_xgb = diff_xgb.sum().sum()
num_differences_ada = diff_ada.sum().sum()

percent_equal_rf = 100-((num_differences_rf / total_cells_rf) * 100)
percent_equal_xgb = 100-((num_differences_xgb / total_cells_xgb) * 100)
percent_equal_ada = 100-((num_differences_ada / total_cells_ada) * 100)

print(f"Percentage of equal cells for Random Forest: {percent_equal_rf:.2f}%")
print(f"Percentage of equal cells for XGBoost: {percent_equal_xgb:.2f}%")
print(f"Percentage of equal cells for AdaBoost: {percent_equal_ada:.2f}%")

Percentage of equal cells for Random Forest: 77.27%
Percentage of equal cells for XGBoost: 78.95%
Percentage of equal cells for AdaBoost: 76.79%

## Final solution

In [486]:
solution = pd.DataFrame({'PassengerId': reduced_data_test.PassengerId, 'Survived': predictions_xgb})
solution.to_csv('submission.csv', index=False)